DROP TABLE BOARD;
CREATE TABLE BOARD (
	BIDX NUMBER PRIMARY KEY,
	BWRITER VARCHAR2(20) NOT NULL,
	BTITLE VARCHAR2(100) NOT NULL,
	BCONTENT VARCHAR2(2000),
	BDATE DATE
);

DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

INSERT INTO BOARD VALUES (9999, '관리자', '공지사항', '공지사항내용', SYSDATE);
COMMIT;
